version: '3.9'
services:
  activemq:
    container_name: activemq
    image: rmohr/activemq:latest
    ports:
      - 8161:8161
      - 61616:61616
  broker:
    build:
      context: ./broker
      dockerfile: Dockerfile
    environment:
      HOST: activemq
    depends_on:
        - activemq
  dodgygeezers:
    build:
      context: ./dodgygeezers
      dockerfile: Dockerfile
    environment:
      HOST: activemq
    depends_on:
      - broker

  girlsallowed:
    build:
      context: ./girlsallowed
      dockerfile: Dockerfile
    environment:
      HOST: activemq
    depends_on:
      - broker

  auldfellas:
    build:
      context: ./auldfellas
      dockerfile: Dockerfile
    environment:
      HOST: activemq
    depends_on:
      - broker

