version: '3.9'
services:
  broker:
    build:
      context: ./broker
      dockerfile: Dockerfile
    ports:
      - "9000:9000"

  dodgygeezers:
    build:
      context: ./dodgygeezers
      dockerfile: Dockerfile
    depends_on:
      - broker

  girlsallowed:
    build:
      context: ./girlsallowed
      dockerfile: Dockerfile
    depends_on:
      - broker

  auldfellas:
    build:
      context: ./auldfellas
      dockerfile: Dockerfile
    depends_on:
      - broker
  core:
    build:
      context: ./core
      dockerfile: Dockerfile